Vagrant.configure("2") do |config|
  # Define server VM (vm1)
  config.vm.define "vm1" do |server|
    server.vm.box = "ubuntu/jammy64"
    server.vm.network "private_network", ip: "192.168.56.10"
    server.vm.hostname = "servidor"
    server.vm.synced_folder ".", "/vagrant_code"
    server.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.gui = true
    end
    server.vm.provision "shell", inline: <<-SHELL
      apt-get update
      # apt-get upgrade -y   # Comentado para evitar demoras y timeouts
      apt-get install -y build-essential net-tools zip joe default-jdk
      cd /vagrant_code
      gcc servidor.c -o servidor
    SHELL
  end

  # Define client VM (vm2)
  config.vm.define "vm2" do |client|
    client.vm.box = "ubuntu/jammy64"
    client.vm.network "private_network", ip: "192.168.56.11"
    client.vm.hostname = "cliente"
    client.vm.synced_folder ".", "/vagrant_code"
    client.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.gui = true
    end
    client.vm.provision "shell", inline: <<-SHELL
      apt-get update
      # apt-get upgrade -y   # Comentado para evitar demoras y timeouts
      apt-get install -y build-essential net-tools zip joe default-jdk
      cd /vagrant_code
      gcc cliente.c -o cliente
    SHELL
  end
end